spring:
  application:
  name: jwtauth

# No muestra el stack-trace de accesos no autorizados en la API
server:
  error:
  include-stacktrace: never

# Conf JWT
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000